CREATE TABLE "TM_OVERSEA_SERVICE" (
  "ID" NUMBER(10,0) NOT NULL,
  "SERVICE_CODE" VARCHAR2(255 BYTE),
  "SERVICE_SECRET" VARCHAR2(500 BYTE),
  "ASC_CODE" VARCHAR2(255 BYTE),
  "ASC_ID" NUMBER,
  "SAP_ACCOUNT" VARCHAR2(255 BYTE),
  "ASC_NAME" VARCHAR2(255 BYTE),
  "CALL_BACK_URL" VARCHAR2(500 BYTE),
  "ONLINE_DATE" DATE,
  "IS_DEL" NUMBER(1,0),
  "REMARK" VARCHAR2(1000 BYTE),
  "CREATE_BY" VARCHAR2(255 BYTE),
  "CREATE_DATE" DATE,
  "UPDATE_BY" VARCHAR2(255 BYTE),
  "UPDATE_DATE" DATE
);
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."ID" IS 'id';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."SERVICE_CODE" IS 'jwt Service Code';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."SERVICE_SECRET" IS 'jwt Service Secret';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."ASC_CODE" IS 'channel code';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."ASC_ID" IS 'channel id';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."SAP_ACCOUNT" IS 'Sap Account';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."ASC_NAME" IS 'Channel Short Name';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."CALL_BACK_URL" IS 'call back url';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."ONLINE_DATE" IS 'online date';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."IS_DEL" IS '0 valid，1 invalid';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."REMARK" IS 'remark';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."CREATE_BY" IS 'write name here';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."CREATE_DATE" IS '';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."UPDATE_BY" IS '';
COMMENT ON COLUMN "TM_OVERSEA_SERVICE"."UPDATE_DATE" IS '';

-- ----------------------------
-- ----------------------------
ALTER TABLE "TM_OVERSEA_SERVICE"  PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TM_OVERSEA_SERVICE
-- ----------------------------
ALTER TABLE "TM_OVERSEA_SERVICE"  CHECK ("ID" IS NOT NULL) ;

-- ----------------------------
-- Indexes structure for table TM_OVERSEA_SERVICE
-- ----------------------------
CREATE INDEX "idx_sCode" ON "TM_OVERSEA_SERVICE" ("SERVICE_CODE" ASC)
